In [1]:
# 1. Load heart disease dataset in pandas dataframe
# 2. Remove outliers using Z score. Usual guideline is to remove anything that has Z score > 3 formula or Z score < -3
# 3. Convert text columns to numbers using label encoding and one hot encoding
# 4. Apply scaling
# 5. Build a classification model using various methods (SVM, logistic regression, random forest) and check which model gives you the best accuracy
# 6. Now use PCA to reduce dimensions, retrain your model and see what impact it has on your model in terms of accuracy. 
# Keep in mind that many times doing PCA reduces the accuracy but computation is much lighter and that's the trade off you need to consider
# while building models in real life

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [5]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [6]:
df[df.Cholesterol>(df.Cholesterol.mean()+3*df.Cholesterol.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
76,32,M,ASY,118,529,0,Normal,130,N,0.0,Flat,1
149,54,M,ASY,130,603,1,Normal,125,Y,1.0,Flat,1
616,67,F,NAP,115,564,0,LVH,160,N,1.6,Flat,0

In [7]:
df.shape

(918, 12)

In [12]:
# identify an outliers
df1 = df[df.Cholesterol<=(df.Cholesterol.mean()+3*df.Cholesterol.std())]
df1.shape

(915, 12)

In [13]:
df[df.MaxHR>(df.MaxHR.mean()+3*df.MaxHR.std())] # no outliers here

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [14]:
df[df.FastingBS>(df.FastingBS.mean()+3*df.FastingBS.std())] # no outliers here

Empty DataFrame
Columns: [Age, Sex, ChestPainType, RestingBP, Cholesterol, FastingBS, RestingECG, MaxHR, ExerciseAngina, Oldpeak, ST_Slope, HeartDisease]
Index: []

In [15]:
df[df.Oldpeak>(df.Oldpeak.mean()+3*df.Oldpeak.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
166,50,M,ASY,140,231,0,ST,140,Y,5.0,Flat,1
702,59,M,TA,178,270,0,LVH,145,N,4.2,Down,0
771,55,M,ASY,140,217,0,Normal,111,Y,5.6,Down,1
791,51,M,ASY,140,298,0,Normal,122,Y,4.2,Flat,1
850,62,F,ASY,160,164,0,LVH,145,N,6.2,Down,1
900,58,M,ASY,114,318,0,ST,140,N,4.4,Down,1

In [36]:
df2 = df1[df1.Oldpeak<=(df1.Oldpeak.mean()+3*df1.Oldpeak.std())]
df2.shape

(909, 12)

In [37]:
df[df.RestingBP>(df.RestingBP.mean()+3*df.RestingBP.std())]

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
109,39,M,ATA,190,241,0,Normal,106,N,0.0,Up,0
241,54,M,ASY,200,198,0,Normal,142,Y,2.0,Flat,1
365,64,F,ASY,200,0,0,Normal,140,Y,1.0,Flat,1
399,61,M,NAP,200,0,1,ST,70,N,0.0,Flat,1
592,61,M,ASY,190,287,1,LVH,150,Y,2.0,Down,1
732,56,F,ASY,200,288,1,LVH,133,Y,4.0,Down,1
759,54,M,ATA,192,283,0,LVH,195,N,0.0,Up,1

In [38]:
df3 = df2[df2.RestingBP<=(df2.RestingBP.mean()+3*df2.RestingBP.std())]
df3.shape

(902, 12)

In [39]:
df.ChestPainType.nunique()

4

In [40]:
df4 = df3.copy()

df4.ExerciseAngina = df4.ExerciseAngina.replace({
    'N': 0,
    'Y':1
})

df4.ST_Slope = df4.ST_Slope.replace({
    'Down':1,
    'Flat': 2,
    'Up': 3
})

df4.RestingECG = df4.RestingECG.replace({
    'Normal': 1,
    'ST': 2,
    'LVH': 3
});

df4.head()

/tmp/ipykernel_29365/216293744.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4.ExerciseAngina = df4.ExerciseAngina.replace({
/tmp/ipykernel_29365/216293744.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4.ST_Slope = df4.ST_Slope.replace({
/tmp/ipykernel_29365/216293744.py:14: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df4.RestingECG = df4.RestingECG.replace({

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,1,172,0,0.0,3,0
1,49,F,NAP,160,180,0,1,156,0,1.0,2,1
2,37,M,ATA,130,283,0,2,98,0,0.0,3,0
3,48,F,ASY,138,214,0,1,108,1,1.5,2,1
4,54,M,NAP,150,195,0,1,122,0,0.0,3,0

In [42]:
df5 = pd.get_dummies(df4, drop_first=True).astype(int)
df5.head()

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA
0,40,140,289,0,1,172,0,0,3,0,1,1,0,0
1,49,160,180,0,1,156,0,1,2,1,0,0,1,0
2,37,130,283,0,2,98,0,0,3,0,1,1,0,0
3,48,138,214,0,1,108,1,1,2,1,0,0,0,0
4,54,150,195,0,1,122,0,0,3,0,1,0,1,0

In [43]:
X = df5.drop("HeartDisease", axis='columns')
y = df5.HeartDisease

In [44]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [45]:
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.24489796, 0.75675676, 0.55791506, ..., 1.        , 0.        ,
        0.        ],
       [0.42857143, 0.86486486, 0.34749035, ..., 0.        , 1.        ,
        0.        ],
       [0.18367347, 0.7027027 , 0.54633205, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.59183673, 0.7027027 , 0.25289575, ..., 0.        , 0.        ,
        0.        ],
       [0.59183673, 0.7027027 , 0.45559846, ..., 1.        , 0.        ,
        0.        ],
       [0.20408163, 0.74594595, 0.33783784, ..., 0.        , 1.        ,
        0.        ]], shape=(902, 13))

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=30)

In [50]:
X_train.shape

(721, 13)

In [51]:
X_test.shape

(181, 13)

In [53]:
# (SVM, logistic regression, random forest)

from sklearn.svm import SVC

In [54]:
svc_model = SVC()

svc_model.fit(X_train, y_train)

SVC()

In [55]:
svc_model.score(X_test, y_test)

0.8453038674033149

In [57]:
# using PCA to reduce number of features or dimensions

from sklearn.decomposition import PCA

In [61]:
pca = PCA(0.95)

X_pca = pca.fit_transform(X)
X_pca.shape

(902, 2)

In [62]:
X.shape

(902, 13)

In [63]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=42)

In [66]:
svc_model.fit(X_train_pca, y_train)
svc_model.score(X_test_pca, y_test) # what you have to remember PCA can some time reduce accuracy but the computation become lighter

0.7071823204419889

In [67]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression()
log_model.fit(X_train, y_train)
log_model.score(X_test, y_test)

0.5138121546961326

In [ ]:
\zx""""""""""""""""""""""""''\]'zxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx