In [1]:
 # find probability of survived based on if he was male, class, age, cabin, fare

In [4]:
import pandas as pd

In [24]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

In [25]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis='columns', inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [26]:
target = df.Survived
inputs = df.drop('Survived', axis='columns')

In [27]:
# convert sex column into numbers becuase only machine learning understand mathematics
dummies = pd.get_dummies(df.Sex)
dummies = dummies.astype(int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [28]:
inputs = pd.concat([inputs, dummies], axis='columns')
inputs.drop('Sex', axis='columns', inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [29]:
inputs.columns[inputs.isna().any()] # checking for null values

Index(['Age'], dtype='object')

In [37]:
df['Age'] = df['Age'].fillna(df.Age.mean())

In [38]:
inputs.columns[inputs.isna().any()] # checking for null values

Index(['Age'], dtype='object')

In [42]:
print(df.Age.isna().sum())

0.0